FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ENV VITE_BACKEND_HOST=http://inventario:8080

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
