package com.art.inventario.dominio;

public enum Accion {
	LOGIN_OK,
	LOGIN_FALLIDO,
	LOGOUT,
	FIN_SESION,
	BLOQUEO_SESION,
	RECUPERAR_ADMIN,
	CAMBIO_CLAVE,
	BLOQUEO_USUARIO,
	DESBLOQUEO_USUARIO,
	CREAR_USUARIO,
	REESTABLECER_CLAVE,
	CAMBIAR_ROL,
	CREAR,
	EDITAR,
	ELIMINAR,
	SUBIR_ARCHIVO,
	DESCARGAR_ARCHIVO,
	BACKUP,
	RESTAURAR,
	IMPORTAR,
	EXPORTAR,
	INSTALACION,
	PETICION
}